### ISSUE TITLE
Update readme.md 

### ISSUE THREAD

**Issue by git-anurag-hub** [git-anurag-hub/social-media-app#6]

**Comment by git-anurag-hub** [comment]
To give the basic idea this app deal similar to Instagram. So you can add something like "It allow to follow peoples and post the images to keep connected".Also you can add something like what te h it uses.

**Comment by AbderrahimSoubaiElidrissi** [comment]
I will take this

**Comment by AbderrahimSoubaiElidrissi** [comment]
Published a PR https://github.com/git-anurag-hub/social-media-app/pull/7

**Comment by andramazo** [comment]
I can take this. Thank you.
