### ISSUE TITLE
Create a image pond

### ISSUE THREAD

**Issue by git-anurag-hub** [git-anurag-hub/social-media-app#8]
Use react pond or something know as image pond to create the preview of the image when user will be uploading it.

**Comment by salonigoyal2309** [comment]
@git-anurag-hub i can work on this :)

**Comment by git-anurag-hub** [comment]
Why not :)

**Comment by salonigoyal2309** [comment]
@git-anurag-hub  please add a .env-example file so that I get to know which variables I need to add

**Comment by git-anurag-hub** [comment]
Added. 
Moreover, if you don't want to provide sendgrid api key what you can do is manually going to the DBMS and changing the field verified of the specific user in users database to 1 from 0.

**Comment by git-anurag-hub** [comment]
Use file pond to create the preview of the image when user is changing the avatar.
